### PR TITLE
feat: add StarkDeFi - [reworked]

### PR DESCRIPTION
**Pull request by iddriss**
#182 

@enitrat here's the new PR

### CODE REVIEW

**Comment by enitrat** [comment]
one last ask: can you integrate this https://github.com/keep-starknet-strange/unruggable.meme/pull/195 to the starkdefi flow?

**Review by enitrat — COMMENTED** [review]
lgtm

**Comment by iddriss** [comment]
> one last ask: can you integrate this #195 to the starkdefi flow?

alright 👍

**Comment by iddriss** [comment]
@enitrat  #195 added.

**Review by enitrat — APPROVED** [review]

**Pull request merged**
