### PR TITLE
feat: add starkdefi integration

### PR DESCRIPTION
**Pull request by iddriss**
Added support for StarkDeFi Dex

### CODE REVIEW

**Review by enitrat — COMMENTED** [review]
awesome! Given that the risks for univ2-like AMMs have already been evaluated at audit times and addressed I see no reason why not to include this in the MVP @AbdelStark. I don't think that would create any extra work for the frontend either, as we can abstract a generic behavior for UNIv2 launches (cc @0xChqrles: can you confirm)

@iddriss thanks for the PR, will look in details once we have addresses some stuff we're prioritizing

**Comment by 0xChqrles** [comment]
It's fine, I can easily adapt the FE to include another UNIv2 👌

**Comment by iddriss** [comment]
@enitrat @AbdelStark any updates on this? anything else you'd want me to work on regarding this? Thanks

**Comment by enitrat** [comment]
@iddriss we had to refactor some internal mechanisms regarding creation and launch due to some vulnerabilities in the Ekubo route, so there might be some conflicts. Could you TAL and rebase? It shouldn't change a lot of stuff for the univ2 (jedi & starkdefi) route, just grouped the initial checks, accounted for the correct lp to supply now that the factory owns 100% of the tokens initially, and distribute the team alloc post-launch

**Comment by enitrat** [comment]
also perhaps the jedi/starkdefi_adapter could be grouped into a generic UniV2 adapter and the only difference between the two would be the call to `add_liquidity` which could be handled in a match statement based on the SupportedExchange type (jedi or starkdefi). But i'm fine keeping things this way if this is simpler

**Comment by iddriss** [comment]
@enitrat Thanks for the update. I'll check it out, it would make sense to have a generic UniV2 adapter, just incase other Univ2 based AMM want to get on boarded and later, possibly a split launch feature to support launching on multiple AMMs at once for tokens that can foot the required liquidity. This is simpler nonetheless.

**Comment by enitrat** [comment]
@iddriss I'm seeing diffs not related to your commits (some changes already existing on main), do you know why?

**Comment by iddriss** [comment]
weird, could be the rebase? let me check

**Comment by iddriss** [comment]
@enitrat the diffs are from the rebase. If that would be a problem I can close this and open a new PR with additions needed for StarkDeFi

**Comment by enitrat** [comment]
yeah please do. So github tracks the modification against the state of main at the time the PR was open? Weird behavior..

**Comment by iddriss** [comment]
Sure thing, the state however will be tracked from the current main branch state. Can't avoid the other diffs if we want the new PR to match the state a the time of this PR. Will open a new PR shortly

**Pull request closed without merging**
